### ISSUE TITLE
'mongoc_collection_count_with_opts' is deprecated

### ISSUE THREAD

**Issue by torben-erz** [asensei/vapor-fluent-mongo#8]
/Sources/MongoSwift/MongoCollection+Read.swift:65:21: 'mongoc_collection_count_with_opts' is deprecated

**Comment by kmahar** [comment]
Hi @torben-erz, that warning is coming from MongoSwift, one of the dependencies of this project (I'm one of MongoSwift's developers). It's because our `count` method for collections is calling a deprecated function from the MongoDB C driver. 
That C driver function is deprecated because MongoDB changed the `count` API with the 4.0 server release. We plan to update MongoSwift to the new API shortly, which will mean we can stop calling the deprecated function and the warning will go away. You can track the work on [SWIFT-133](https://jira.mongodb.org/browse/SWIFT-133).

**Comment by torben-erz** [comment]
Thank you for the information
